version: "3.7"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    container_name: es01
    restart: always
    hostname: es01
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: -Xms500m -Xmx500m
    ports:
      - 9200:9200
    networks:
      - trino-ranger-demo
    volumes:
    - ranger-es-data:/usr/share/elasticsearch/data
  postgresql:
    image: postgres:13
    container_name: psql01
    restart: always
    hostname: psql01
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - 5432:5432
    networks:
      - trino-ranger-demo
    volumes:
    - ranger-pg-data:/var/lib/postgresql/data
  ranger-admin:
    image: aakashnand/trino-ranger-demo:v4.0
    #build: ranger-admin
    container_name: ranger-admin
    hostname: ranger-admin
    restart: always
    entrypoint: /root/ranger-admin/docker-entrypoint.sh
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 6G
        reservations:
          cpus: '1'
          memory: 5G
    ports:
      - 6080:6080
      - 6182:6182
    networks:
      - trino-ranger-demo
    volumes:
      - ./ranger-admin:/root/ranger-admin
  trino:
    image: trinodb/trino:436
    hostname: localhost-trino
    user: root
    container_name: localhost-trino
    restart: always
    entrypoint: /root/docker-entrypoint.sh
    networks:
      - trino-ranger-demo
    volumes:
      - ./trino/install.properties:/root/install.properties
      - ./trino/docker-entrypoint.sh:/root/docker-entrypoint.sh
      - ./trino/tls/test-ssl-keystore.jks:/root/test-ssl-keystore.jks
    ports:
      - 8080:8080
networks:
  trino-ranger-demo:
    driver: bridge
volumes:
  ranger-es-data:
  ranger-pg-data:
